-- AccurateCurioNames_localization.lua

local localizations = {

-- ===============================================================================
-- DESCRIPTION AND SETTINGS
-- ===============================================================================
	mod_name = {
		en = "Accurate Curio Names",
		ru = "Точные названия реликвий",
		fr = "Noms précis des reliques",
		de = "Präzise Reliktnamen",
		es = "Nombres precisos de reliquias",
		it = "Nomi precisi delle reliquie",
		ja = "正確なキュリオ名",
		ko = "정확한 큐리오 이름",
		pl = "Precyzyjne nazwy reliktów",
 ["pt-br"] = "Nomes precisos de relíquias",
 ["zh-cn"] = "精确圣物名称",
 ["zh-tw"] = "精確聖物名稱",
	},
	mod_description = {
		en = "Changes each reliquary's name to its blessing (and optionally perks) with abbreviations.",
		ru = "Accurate Curio Names - Меняет название каждой реликвии на её благословение (и опционально перки) с сокращениями.",
		fr = "Change le nom de chaque relique en sa bénédiction (et éventuellement les avantages) avec abréviations.",
		de = "Ändert den Namen jedes Relikts in seinen Segen (und optional Vorteile) mit Abkürzungen.",
		es = "Cambia el nombre de cada reliquia por su bendición (y opcionalmente ventajas) con abreviaturas.",
		it = "Cambia il nome di ogni reliquia nella sua benedizione (e opzionalmente vantaggi) con abbreviazioni.",
		ja = "各キュリオの名前を祝福（オプションでパーク）に変更し、略語を使用します。",
		ko = "각 큐리오의 이름을 축복(선택적으로 특전)으로 변경하고 약어를 사용합니다.",
		pl = "Zmienia nazwę każdego reliktu na jego błogosławieństwo (i opcjonalnie atuty) z użyciem skrótów.",
 ["pt-br"] = "Altera o nome de cada relíquia para sua bênção (e opcionalmente vantagens) com abreviações.",
 ["zh-cn"] = "将每个圣物的名称更改为其祝福（可选特长），并使用缩写。",
 ["zh-tw"] = "將每個聖物的名稱改為其祝福（可選特長），並使用縮寫。",
	},

	other_mod_override = {
		en = "Respect Custom Naming",
		ru = "Приоритет пользовательских имён",
		fr = "Respecter les noms personnalisés",
		de = "Benutzerdefinierte Namen respektieren",
		es = "Respetar nombres personalizados",
		it = "Rispetta nomi personalizzati",
		ja = "カスタム命名を尊重",
		ko = "커스텀 이름 존중",
		pl = "Szanuj niestandardowe nazwy",
 ["pt-br"] = "Respeitar nomes personalizados",
 ["zh-cn"] = "尊重自定义命名",
 ["zh-tw"] = "尊重自訂名稱",
	},
	other_mod_override_description = {
		en = "Allow custom reliquary names from other mods (like Name It) to override Accurate Curio Names if a custom name exists.",
		ru = "Разрешить пользовательским названиям реликвий из других модов (например, Name It) перезаписывать настройки этого мода, если пользовательское имя существует.",
		fr = "Permettre aux noms personnalisés de reliques d'autres mods (comme Name It) d'écraser Noms précis des reliques si un nom personnalisé existe.",
		de = "Erlauben Sie benutzerdefinierten Reliktnamen aus anderen Mods (z. B. Name It), präzise Reliktnamen zu überschreiben, wenn ein benutzerdefinierter Name existiert.",
		es = "Permitir que los nombres personalizados de reliquias de otros mods (como Name It) sobrescriban Nombres precisos de reliquias si existe un nombre personalizado.",
		it = "Consenti ai nomi personalizzati delle reliquie di altri mod (come Name It) di sovrascrivere Nomi precisi delle reliquie se esiste un nome personalizzato.",
		ja = "他のMOD（Name Itなど）からのカスタムキュリオ名が存在する場合、正確なキュリオ名を上書きすることを許可します。",
		ko = "다른 모드(예: Name It)에서 온 커스텀 큐리오 이름이 존재할 경우 정확한 큐리오 이름을 덮어쓰도록 허용합니다.",
		pl = "Zezwól na niestandardowe nazwy reliktów z innych modów (np. Name It) na nadpisanie precyzyjnych nazw, jeśli istnieje niestandardowa nazwa.",
 ["pt-br"] = "Permitir que nomes personalizados de relíquias de outros mods (como Name It) substituam Nomes precisos de relíquias se um nome personalizado existir.",
 ["zh-cn"] = "允许其他模组 (如 Name It) 的自定义圣物名称在存在自定义名称时覆盖精确圣物名称。",
 ["zh-tw"] = "允許其他模組（例如 Name It）的自訂聖物名稱在存在自訂名稱時覆蓋精確聖物名稱。",
	},

	show_perks = {
		en = "Display Perks in the Curio's Name",
		ru = "Показывать перки в названиях реликвий",
		fr = "Afficher les avantages dans le nom de la relique",
		de = "Vorteile im Reliktnamen anzeigen",
		es = "Mostrar ventajas en el nombre de la reliquia",
		it = "Mostra i vantaggi nel nome della reliquia",
		ja = "キュリオの名前にパークを表示",
		ko = "큐리오 이름에 특전 표시",
		pl = "Wyświetlaj atuty w nazwie reliktu",
 ["pt-br"] = "Exibir vantagens no nome da relíquia",
 ["zh-cn"] = "在圣物名称中显示特长",
 ["zh-tw"] = "在聖物名稱中顯示特長",
	},
	show_perks_description = {
		en = "Show perks in the name of the reliquary. Perks are always abbreviated.",
		ru = "Показывать перки в названии реликвий. Перки всегда показываются кратко.",
		fr = "Afficher les avantages dans le nom de la relique. Les avantages sont toujours abrégés.",
		de = "Vorteile im Namen des Relikts anzeigen. Vorteile werden immer abgekürzt.",
		es = "Mostrar ventajas en el nombre de la reliquia. Las ventajas siempre se abrevian.",
		it = "Mostra i vantaggi nel nome della reliquia. I vantaggi sono sempre abbreviati.",
		ja = "キュリオの名前にパークを表示。パークは常に省略されます。",
		ko = "큐리오 이름에 특전 표시. 특전은 항상 약어로 표시됩니다.",
		pl = "Wyświetlaj atuty w nazwie reliktu. Atuty są zawsze skracane.",
 ["pt-br"] = "Exibir vantagens no nome da relíquia. As vantagens são sempre abreviadas.",
 ["zh-cn"] = "在圣物名称中显示特长。特长始终使用缩写。",
 ["zh-tw"] = "在聖物名稱中顯示特長。特長始終使用縮寫。",
	},

	blessing_format = {
		en = "Blessing Name Format",
		ru = "Формат названия благословения",
		fr = "Format du nom de la bénédiction",
		de = "Format des Segensnamens",
		es = "Formato del nombre de la bendición",
		it = "Formato del nome della benedizione",
		ja = "祝福名の形式",
		ko = "축복 이름 형식",
		pl = "Format nazwy błogosławieństwa",
 ["pt-br"] = "Formato do nome da bênção",
 ["zh-cn"] = "祝福名称格式",
 ["zh-tw"] = "祝福名稱格式",
	},
	blessing_format_description = {
		en = "Format for displaying blessings in the curio name. This setting does not affect perks.\n\nTakes the default description from the game or the description from Enhanced Descriptions.",
		ru = "Формат отображения благословений в названии реликвии. На перки эта настройка не влияет.\n\nБерёт стандартное описание из игры или описание из Enhanced Descriptions.",
		fr = "Format d'affichage des bénédictions dans le nom de la curiosité. Ce paramètre n'affecte pas les avantages.\n\nPrend la description par défaut du jeu ou la description d'Enhanced Descriptions.",
		de = "Format zur Anzeige von Segnungen im Namen des Kuriosums. Diese Einstellung wirkt sich nicht auf Perks aus.\n\nVerwendet die Standardbeschreibung aus dem Spiel oder die Beschreibung aus Enhanced Descriptions.",
		es = "Formato para mostrar bendiciones en el nombre de la curiosidad. Esta configuración no afecta a los perks.\n\nToma la descripción predeterminada del juego o la descripción de Enhanced Descriptions.",
		it = "Formato per visualizzare le benedizioni nel nome della curiosità. Questa impostazione non influisce sui perk.\n\nPrende la descrizione predefinita dal gioco o la descrizione da Enhanced Descriptions.",
		ja = "キュリオ名における祝福の表示形式。この設定はパークには影響しません。\n\nゲームのデフォルト説明または Enhanced Descriptions の説明を使用します。",
		ko = "큐리오 이름에 축복을 표시하는 형식입니다. 이 설정은 특전에 영향을 주지 않습니다.\n\n게임의 기본 설명 또는 Enhanced Descriptions의 설명을 사용합니다.",
		pl = "Format wyświetlania błogosławieństw w nazwie reliktu. To ustawienie nie wpływa na perki.\n\nPobiera domyślny opis z gry lub opis z Enhanced Descriptions.",
 ["pt-br"] = "Formato para exibir bênçãos no nome da curiosidade. Esta configuração não afeta os perks.\n\nPega a descrição padrão do jogo ou a descrição do Enhanced Descriptions.",
 ["zh-cn"] = "在圣物名称中显示祝福的格式。此设置不影响特长。\n\n采用游戏默认描述或 Enhanced Descriptions 的描述。",
 ["zh-tw"] = "在聖物名稱中顯示祝福的格式。此設定不影響特長。\n\n採用遊戲預設描述或 Enhanced Descriptions 的描述。",
	},
	blessing_format_standard = {
		en = "Standard",
		ru = "Стандартный",
		fr = "Standard",
		de = "Standard",
		es = "Estándar",
		it = "Standard",
		ja = "標準",
		ko = "표준",
		pl = "Standardowy",
 ["pt-br"] = "Padrão",
 ["zh-cn"] = "标准",
 ["zh-tw"] = "標準",
	},
	blessing_format_short = {
		en = "Short",
		ru = "Кратко",
		fr = "Court",
		de = "Kurz",
		es = "Corto",
		it = "Breve",
		ja = "短い",
		ko = "짧게",
		pl = "Krótko",
 ["pt-br"] = "Curto",
 ["zh-cn"] = "简短",
 ["zh-tw"] = "簡短",
	},
	blessing_format_very_short = {
		en = "Abbreviation",
		ru = "Аббревиатура",
		fr = "Abréviation",
		de = "Abkürzung",
		es = "Abreviatura",
		it = "Abbreviazione",
		ja = "略語",
		ko = "약어",
		pl = "Abrewiatura",
 ["pt-br"] = "Abreviação",
 ["zh-cn"] = "缩写",
 ["zh-tw"] = "縮寫",
	},

-- ===============================================================================
-- BLESSINGS
-- ===============================================================================

-- HEALTH
	acu_health_abbr = {
		en = "HP",
		ru = "ЗДОР",
		fr = "PV",
		de = "LP",
		es = "PS",
		it = "PS",
		ja = "HP",
		ko = "HP",
		pl = "HP",
 ["pt-br"] = "PV",
 ["zh-cn"] = "生命",
 ["zh-tw"] = "生命",
	},
	acu_health_word = {
		en = "Health",
		ru = "к здоровью",
		fr = "Santé",
		de = "Gesundheit",
		es = "Salud",
		it = "Salute",
		ja = "ヘルス",
		ko = "체력",
		pl = "Zdrowie",
 ["pt-br"] = "Saúde",
 ["zh-cn"] = "生命值",
 ["zh-tw"] = "生命值",
	},

-- STAMINA
	acu_stamina_abbr = {
		en = "STM",
		ru = "ВНСЛ",
		fr = "END",
		de = "AUS",
		es = "AGU",
		it = "VIG",
		ja = "スタ",
		ko = "스태",
		pl = "WYT",
 ["pt-br"] = "VIG",
 ["zh-cn"] = "体力",
 ["zh-tw"] = "耐力",
	},
	acu_stamina_word = {
		en = "Stamina",
		ru = "к выносливости",
		fr = "Endurance",
		de = "Ausdauer",
		es = "Resistencia",
		it = "Stamina",
		ja = "スタミナ",
		ko = "스태미나",
		pl = "Wytrzymałość",
 ["pt-br"] = "Resistência",
 ["zh-cn"] = "耐力",
 ["zh-tw"] = "耐力",
	},

-- TOUGHNESS
	acu_toughness_abbr = {
		en = "THN",
		ru = "СТЙК",
		fr = "ROB",
		de = "ZÄH",
		es = "DUR",
		it = "TEN",
		ja = "耐",
		ko = "강인",
		pl = "ODP",
 ["pt-br"] = "RES",
 ["zh-cn"] = "韧性",
 ["zh-tw"] = "韌性",
	},
	acu_toughness_word = {
		en = "Toughness",
		ru = "к стойкости",
		fr = "Robustesse",
		de = "Widerstandskraft",
		es = "Resistencia",
		it = "Robustezza",
		ja = "タフネス",
		ko = "강인함",
		pl = "Odporność",
 ["pt-br"] = "Resistência",
 ["zh-cn"] = "韧性",
 ["zh-tw"] = "韌性",
	},

-- WOUND
	acu_wound_abbr = {
		en = "WND",
		ru = "РАНА",
		fr = "BLS",
		de = "WND",
		es = "HRD",
		it = "FRT",
		ja = "傷",
		ko = "상처",
		pl = "RN",
 ["pt-br"] = "FRT",
 ["zh-cn"] = "伤口",
 ["zh-tw"] = "傷痕",
	},
	acu_wound_word = {
		en = "Wound",
		ru = "рана",
		fr = "Blessure",
		de = "Wunde",
		es = "Herida",
		it = "Ferita",
		ja = "負傷",
		ko = "상처",
		pl = "Rana",
 ["pt-br"] = "Ferida",
 ["zh-cn"] = "伤口",
 ["zh-tw"] = "傷痕",
	},

-- ===============================================================================
-- PERKS
-- ===============================================================================

-- ALLY REVIVE SPEED
	acu_revive_spd_abbr = {
		en = "Rev Spd",
		ru = "скор возр.",
		fr = "Réanim.",
		de = "Wiederbeleb.",
		es = "Revivir",
		it = "Rianim.",
		ja = "蘇生",
		ko = "부활",
		pl = "Ożywianie",
 ["pt-br"] = "Reviver",
 ["zh-cn"] = "复活",
 ["zh-tw"] = "復活",
	},
	acu_revive_spd_word = {
		en = "Ally Revive Speed",
		ru = "к скорости возрождения союзников",
		fr = "à la Vitesse de Réanimation des Alliés",
		de = "zur Wiederbelebungsgeschwindigkeit von Verbündeten",
		es = "a la Velocidad de Revivir Aliados",
		it = "alla Velocità di Rianimazione Alleati",
		ja = "味方蘇生速度",
		ko = "아군 부활 속도",
		pl = "do Szybkości Ożywiania Sojuszników",
 ["pt-br"] = "à Velocidade de Reviver Aliados",
 ["zh-cn"] = "队友复活速度",
 ["zh-tw"] = "隊友復活速度",
	},

-- BLOCK COST REDUCTION
	acu_block_cost_abbr = {
		en = "Block Cost",
		ru = "стоим. блока",
		fr = "Coût Bloc",
		de = "Blockkosten",
		es = "Costo Bloqueo",
		it = "Costo Blocco",
		ja = "ブロック消費",
		ko = "블록 비용",
		pl = "Koszt Bloku",
 ["pt-br"] = "Custo Bloqueio",
 ["zh-cn"] = "格挡消耗",
 ["zh-tw"] = "格擋消耗",
	},
	acu_block_cost_word = {
		en = "Block Cost Reduction",
		ru = "к снижению стоимости блока",
		fr = "à la Réduction du Coût de Blocage",
		de = "zur Blockkostenreduktion",
		es = "a la Reducción del Costo de Bloqueo",
		it = "alla Riduzione del Costo di Blocco",
		ja = "ブロック消費軽減",
		ko = "블록 비용 감소",
		pl = "do Redukcji Kosztu Blokady",
 ["pt-br"] = "à Redução do Custo de Bloqueio",
 ["zh-cn"] = "格挡消耗降低",
 ["zh-tw"] = "格擋消耗降低",
	},

-- COMBAT ABILITY REGENERATION
	acu_cooldown_abbr = {
		en = "Abil Reg",
		ru = "восст. спос.",
		fr = "Régén. Abil",
		de = "Abil-Regen",
		es = "Reg. Abil",
		it = "Rig. Abil",
		ja = "ウルト回復",
		ko = "궁극기 회복",
		pl = "Regen. Abil",
 ["pt-br"] = "Reg. Abil",
 ["zh-cn"] = "技能回复",
 ["zh-tw"] = "技能回復",
	},
	acu_cooldown_word = {
		en = "Combat Ability Regeneration",
		ru = "к восстановлению способности",
		fr = "à la Régénération de Capacité de Combat",
		de = "zur Kampffähigkeits-Regeneration",
		es = "a la Regeneración de Habilidad de Combate",
		it = "alla Rigenerazione dell'Abilità di Combattimento",
		ja = "戦闘スキル回復",
		ko = "전투 능력 재생성",
		pl = "do Regeneracji Umiejętności Bojowej",
 ["pt-br"] = "à Regeneração de Habilidade de Combate",
 ["zh-cn"] = "作战技能回复",
 ["zh-tw"] = "戰鬥技能回復",
	},

-- CORRUPTION RESISTANCE
	acu_corruption_res_abbr = {
		en = "Corr Res",
		ru = "сопр. порче",
		fr = "Rés. Corr",
		de = "Verderb.-Res.",
		es = "Res. Corr",
		it = "Res. Corr",
		ja = "腐敗耐性",
		ko = "타락 저항",
		pl = "Odp. Skazy",
 ["pt-br"] = "Res. Corr",
 ["zh-cn"] = "腐化抗性",
 ["zh-tw"] = "腐敗抗性",
	},
	acu_corruption_res_word = {
		en = "Corruption Resistance",
		ru = "к сопротивлению порче",
		fr = "à la Résistance à la Corruption",
		de = "zum Verderbniswiderstand",
		es = "a la Resistencia a la Corrupción",
		it = "alla Resistenza alla Corruzione",
		ja = "腐敗耐性",
		ko = "타락 저항",
		pl = "do Odporności na Skazę",
 ["pt-br"] = "à Resistência à Corrupção",
 ["zh-cn"] = "腐化抗性",
 ["zh-tw"] = "腐敗抗性",
	},

-- CORRUPTION RESISTANCE FROM GRIMOIRES
	acu_grim_res_abbr = {
		en = "Grim Res",
		ru = "сопр. порче грим.",
		fr = "Rés. Grim",
		de = "Grim-Res.",
		es = "Res. Grim",
		it = "Res. Grim",
		ja = "魔道書耐性",
		ko = "마도서 저항",
		pl = "Odp. Grim",
 ["pt-br"] = "Res. Grim",
 ["zh-cn"] = "魔法书抗性",
 ["zh-tw"] = "法術書抗性",
	},
	acu_grim_res_word = {
		en = "Corruption Resistance from Grimoires",
		ru = "к сопротивлению порче от гримуаров",
		fr = "à la Résistance à la Corruption (Grimoires)",
		de = "zum Verderbniswiderstand (Grimoires)",
		es = "a la Resistencia a la Corrupción (Grimorios)",
		it = "alla Resistenza alla Corruzione (Grimori)",
		ja = "魔道書による腐敗耐性",
		ko = "마도서 타락 저항",
		pl = "do Odporności na Skazę (Grimoires)",
 ["pt-br"] = "à Resistência à Corrupção (Grimórios)",
 ["zh-cn"] = "魔法书腐化抗性",
 ["zh-tw"] = "法術書腐敗抗性",
	},

-- CURIO AS MISSION REWARD
	acu_curio_chance_abbr = {
		en = "Curio Chnc",
		ru = "шанс на релик.",
		fr = "Chance Relique",
		de = "Relikt-Chance",
		es = "Prob. Reliquia",
		it = "Prob. Reliquia",
		ja = "珍品確率",
		ko = "진품 확률",
		pl = "Szansa Reliktu",
 ["pt-br"] = "Chance Relíquia",
 ["zh-cn"] = "圣物几率",
 ["zh-tw"] = "聖物機率",
	},
	acu_curio_chance_word = {
		en = "Curio Drop Chance",
		ru = "к шансу получения реликвий",
		fr = "à la Chance d'Obtention d'une Relique",
		de = "zur Relikt-Drop-Chance",
		es = "a la Probabilidad de Reliquia",
		it = "alla Probabilità di Reliquia",
		ja = "珍品ドロップ確率",
		ko = "진품 획득 확률",
		pl = "do Szansy na Relikt",
 ["pt-br"] = "à Chance de Obter Relíquia",
 ["zh-cn"] = "圣物掉落几率",
 ["zh-tw"] = "聖物掉落機率",
	},

-- DAMAGE RESISTANCE VS BOMBERS
	acu_bomber_res_abbr = {
		en = "Bomber Res",
		ru = "сопр. гренад.",
		fr = "Rés. Bomb.",
		de = "Bomber-Res.",
		es = "Res. Bombard.",
		it = "Res. Bombar.",
		ja = "爆撃耐性",
		ko = "폭격 저항",
		pl = "Odp. Bombow.",
 ["pt-br"] = "Res. Bomb.",
 ["zh-cn"] = "轰炸抗性",
 ["zh-tw"] = "轟炸抗性",
	},
	acu_bomber_res_word = {
		en = "Damage Resistance vs Bombers",
		ru = "к сопротивлению урону от гренадёров",
		fr = "à la Résistance aux Dégâts (Bombardiers)",
		de = "zum Schadenswiderstand gegen Bomber",
		es = "a la Resistencia al Daño (Bombarderos)",
		it = "alla Resistenza ai Danni (Bombaroli)",
		ja = "爆撃兵へのダメージ耐性",
		ko = "폭격수 피해 저항",
		pl = "do Odporności na Obrażenia (Bombardierzy)",
 ["pt-br"] = "à Resistência a Dano (Bombardeiros)",
 ["zh-cn"] = "轰炸者伤害抗性",
 ["zh-tw"] = "轟炸者傷害抗性",
	},

-- DAMAGE RESISTANCE VS FLAMERS
	acu_flamer_res_abbr = {
		en = "Flamer Res",
		ru = "сопр. огнем.",
		fr = "Rés. Incend.",
		de = "Flammen-Res.",
		es = "Res. Lanzall.",
		it = "Res. Lanciaf.",
		ja = "火炎耐性",
		ko = "화염 저항",
		pl = "Odp. Ognia",
 ["pt-br"] = "Res. Lança-chamas",
 ["zh-cn"] = "火焰抗性",
 ["zh-tw"] = "火焰抗性",
	},
	acu_flamer_res_word = {
		en = "Damage Resistance vs Flamers",
		ru = "к сопротивлению урону от огнемётчиков",
		fr = "à la Résistance aux Dégâts (Incendiaires)",
		de = "zum Schadenswiderstand gegen Flammenwerfer",
		es = "a la Resistencia al Daño (Lanzallamas)",
		it = "alla Resistenza ai Danni (Lanciafiamme)",
		ja = "火炎放射兵へのダメージ耐性",
		ko = "화염방사병 피해 저항",
		pl = "do Odporności na Obrażenia (Miotacze Ognia)",
 ["pt-br"] = "à Resistência a Dano (Lança-chamas)",
 ["zh-cn"] = "火焰兵伤害抗性",
 ["zh-tw"] = "火焰兵傷害抗性",
	},

-- DAMAGE RESISTANCE VS GUNNERS
	acu_gunner_res_abbr = {
		en = "Gunner Res",
		ru = "сопр. пулем.",
		fr = "Rés. Mitr.",
		de = "Schützen-Res.",
		es = "Res. Fusil.",
		it = "Res. Mitrag.",
		ja = "銃手耐性",
		ko = "사수 저항",
		pl = "Odp. Strzelców",
 ["pt-br"] = "Res. Atirad.",
 ["zh-cn"] = "炮手抗性",
 ["zh-tw"] = "砲手抗性",
	},
	acu_gunner_res_word = {
		en = "Damage Resistance vs Gunners",
		ru = "к сопротивлению урону от пулемётчиков",
		fr = "à la Résistance aux Dégâts (Mitrailleurs)",
		de = "zum Schadenswiderstand gegen Schützen",
		es = "a la Resistencia al Daño (Fusileros)",
		it = "alla Resistenza ai Danni (Mitraglieri)",
		ja = "銃手へのダメージ耐性",
		ko = "사수 피해 저항",
		pl = "do Odporności na Obrażenia (Strzelcy)",
 ["pt-br"] = "à Resistência a Dano (Atiradores)",
 ["zh-cn"] = "炮手伤害抗性",
 ["zh-tw"] = "砲手傷害抗性",
	},

-- DAMAGE RESISTANCE VS MUTANTS
	acu_mutant_res_abbr = {
		en = "Mutant Res",
		ru = "сопр. мут.",
		fr = "Rés. Mutants",
		de = "Mutanten-Res.",
		es = "Res. Mutantes",
		it = "Res. Mutanti",
		ja = "ミュータント耐性",
		ko = "돌연변이 저항",
		pl = "Odp. Mutantów",
 ["pt-br"] = "Res. Mutantes",
 ["zh-cn"] = "变种人抗性",
 ["zh-tw"] = "變種人抗性",
	},
	acu_mutant_res_word = {
		en = "Damage Resistance vs Mutants",
		ru = "к сопротивлению урону от мутантов",
		fr = "à la Résistance aux Dégâts (Mutants)",
		de = "zum Schadenswiderstand gegen Mutanten",
		es = "a la Resistencia al Daño (Mutantes)",
		it = "alla Resistenza ai Danni (Mutanti)",
		ja = "ミュータントへのダメージ耐性",
		ko = "돌연변이 피해 저항",
		pl = "do Odporności na Obrażenia (Mutanci)",
 ["pt-br"] = "à Resistência a Dano (Mutantes)",
 ["zh-cn"] = "变种人伤害抗性",
 ["zh-tw"] = "變種人傷害抗性",
	},

-- DAMAGE RESISTANCE VS POX HOUNDS
	acu_hound_res_abbr = {
		en = "Hound Res",
		ru = "сопр. гонч.",
		fr = "Rés. Cerd.",
		de = "Pesthund-Res.",
		es = "Res. Sabuesos",
		it = "Res. Segugi",
		ja = "ハウンド耐性",
		ko = "사냥개 저항",
		pl = "Odp. Szczurów",
 ["pt-br"] = "Res. Cães",
 ["zh-cn"] = "猎犬抗性",
 ["zh-tw"] = "獵犬抗性",
	},
	acu_hound_res_word = {
		en = "Damage Resistance vs Pox Hounds",
		ru = "к сопротивлению урону от чумных гончих",
		fr = "à la Résistance aux Dégâts (Cerdères vérolés)",
		de = "zum Schadenswiderstand gegen Pesthunde",
		es = "a la Resistencia al Daño (Sabuesos de la Peste)",
		it = "alla Resistenza ai Danni (Segugi del Vaiolo)",
		ja = "ポックスハウンドへのダメージ耐性",
		ko = "역병 사냥개 피해 저항",
		pl = "do Odporności na Obrażenia (Szczury Zarazy)",
 ["pt-br"] = "à Resistência a Dano (Cães da Peste)",
 ["zh-cn"] = "瘟疫猎犬伤害抗性",
 ["zh-tw"] = "瘟疫獵犬傷害抗性",
	},

-- DAMAGE RESISTANCE VS SNIPERS
	acu_sniper_res_abbr = {
		en = "Sniper Res",
		ru = "сопр. снайп.",
		fr = "Rés. Snip.",
		de = "Scharfsch.-Res.",
		es = "Res. Franc.",
		it = "Res. Cecch.",
		ja = "狙撃手耐性",
		ko = "저격수 저항",
		pl = "Odp. Snajp.",
 ["pt-br"] = "Res. Atirad. Elite",
 ["zh-cn"] = "狙击手抗性",
 ["zh-tw"] = "狙擊手抗性",
	},
	acu_sniper_res_word = {
		en = "Damage Resistance vs Snipers",
		ru = "к сопротивлению урону от снайперов",
		fr = "à la Résistance aux Dégâts (Snipers)",
		de = "zum Schadenswiderstand gegen Scharfschützen",
		es = "a la Resistencia al Daño (Francotiradores)",
		it = "alla Resistenza ai Danni (Cecchini)",
		ja = "狙撃兵へのダメージ耐性",
		ko = "저격수 피해 저항",
		pl = "do Odporności na Obrażenia (Snajperzy)",
 ["pt-br"] = "à Resistência a Dano (Atiradores de Elite)",
 ["zh-cn"] = "狙击手伤害抗性",
 ["zh-tw"] = "狙擊手傷害抗性",
	},

-- EXPERIENCE
	acu_xp_abbr = {
		en = "XP",
		ru = "опыт",
		fr = "XP",
		de = "EP",
		es = "EXP",
		it = "ESP",
		ja = "経験値",
		ko = "경험치",
		pl = "PD",
 ["pt-br"] = "EXP",
 ["zh-cn"] = "经验",
 ["zh-tw"] = "經驗",
	},
	acu_xp_word = {
		en = "Experience",
		ru = "к опыту",
		fr = "à l'Expérience",
		de = "zur Erfahrung",
		es = "a la Experiencia",
		it = "all'Esperienza",
		ja = "経験値",
		ko = "경험치",
		pl = "do Doświadczenia",
 ["pt-br"] = "à Experiência",
 ["zh-cn"] = "经验",
 ["zh-tw"] = "經驗",
	},

-- ORDO DOCKETS
	acu_dockets_abbr = {
		en = "Dockets",
		ru = "ордо",
		fr = "Bordereaux",
		de = "Ordo-Marken",
		es = "Documentos",
		it = "Cedole",
		ja = "書類",
		ko = "오르도 문서",
		pl = "Mandaty",
 ["pt-br"] = "Notas",
 ["zh-cn"] = "双子币",
 ["zh-tw"] = "教團標籤",
	},
	acu_dockets_word = {
		en = "Ordo Dockets",
		ru = "к купонам ордо",
		fr = "aux Bordereaux de l'Ordo",
		de = "zu Ordo-Marken",
		es = "a los Documentos de la Ordo",
		it = "alle Cedole dell'Ordo",
		ja = "オルド書類",
		ko = "오르도 문서",
		pl = "do Mandatów Ordo",
 ["pt-br"] = "às Notas da Ordo",
 ["zh-cn"] = "审判庭双子币",
 ["zh-tw"] = "教團標籤",
	},

-- STAMINA SPRINT COST REDUCTION
	acu_stam_sprint_abbr = {
		en = "Stam Spr Cost Red",
		ru = "затр. вын. на бег",
		fr = "Réduc. coût sprint endur.",
		de = "Ausd. Sprintkosten-Red.",
		es = "Red. coste sprint resist.",
		it = "Rid. costo sprint stamina",
		ja = "スプリントスタミナコスト減",
		ko = "스프린트 스태미나 비용 감소",
		pl = "Red. kosztu sprintu wytrz.",
		["pt-br"] = "Red. custo corrida resist.",
		["zh-cn"] = "冲刺耐力消耗降低",
		["zh-tw"] = "衝刺耐力消耗降低",
	},
	acu_stam_sprint_word = {
		en = "Stamina Sprint Cost Reduction",
		ru = "к снижению затрат выносливости на бег",
		fr = "Réduction du coût d'endurance en sprint",
		de = "Verringerung der Ausdauerkosten beim Sprinten",
		es = "Reducción del coste de resistencia al esprintar",
		it = "Riduzione del costo di stamina per lo sprint",
		ja = "スプリントのスタミナコスト減少",
		ko = "스프린트 스태미나 비용 감소",
		pl = "Redukcja kosztu wytrzymałości podczas sprintu",
		["pt-br"] = "Redução do custo de resistência ao correr",
		["zh-cn"] = "冲刺耐力消耗降低",
		["zh-tw"] = "衝刺耐力消耗降低",
	},

-- STAMINA REGENERATION
	acu_stam_regen_abbr = {
		en = "Stam Reg",
		ru = "восст. вын.",
		fr = "Régén. Endur.",
		de = "Ausd.-Regen.",
		es = "Reg. Aguante",
		it = "Rig. Vigore",
		ja = "スタ回復",
		ko = "스태 회복",
		pl = "Regen. Wyt.",
 ["pt-br"] = "Reg. Vigor",
 ["zh-cn"] = "体力回复",
 ["zh-tw"] = "耐力回復",
	},
	acu_stam_regen_word = {
		en = "Stamina Regeneration",
		ru = "к восстановлению выносливости",
		fr = "à la Régénération d'Endurance",
		de = "zur Ausdauer-Regeneration",
		es = "a la Regeneración de Aguante",
		it = "alla Rigenerazione del Vigore",
		ja = "スタミナ回復",
		ko = "스태미나 재생성",
		pl = "do Regeneracji Wytrzymałości",
 ["pt-br"] = "à Regeneração de Vigor",
 ["zh-cn"] = "体力回复",
 ["zh-tw"] = "耐力回復",
	},

-- TOUGHNESS REGENERATION SPEED
	acu_tn_regen_abbr = {
		en = "Tghn Reg",
		ru = "скор. восст. стойк.",
		fr = "Régén. Rob.",
		de = "Zäh.-Regen.",
		es = "Reg. Dureza",
		it = "Rig. Tenacia",
		ja = "耐回復",
		ko = "강인 회복",
		pl = "Regen. Odp.",
 ["pt-br"] = "Reg. Resist.",
 ["zh-cn"] = "韧性回复",
 ["zh-tw"] = "韌性回復",
	},
	acu_tn_regen_word = {
		en = "Toughness Regeneration Speed",
		ru = "к скорости восстановления стойкости",
		fr = "à la Vitesse de Régénération de Robustesse",
		de = "zur Zähigkeits-Regenerationsgeschwindigkeit",
		es = "a la Velocidad de Regeneración de Dureza",
		it = "alla Velocità di Rigenerazione della Tenacia",
		ja = "耐久力回復速度",
		ko = "강인함 재생성 속도",
		pl = "do Szybkości Regeneracji Odporności",
 ["pt-br"] = "à Velocidade de Regeneração de Resistência",
 ["zh-cn"] = "韧性回复速度",
 ["zh-tw"] = "韌性回復速度",
	},
}

return localizations
